---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blackbox-exporter
  name: blackbox-exporter
spec:
  ports:
  - name: 9115-tcp
    port: 9115
    protocol: TCP
    targetPort: 9115
  selector:
    app: blackbox-exporter
    deploymentconfig: blackbox-exporter

---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: blackbox-exporter
  name: blackbox-exporter
spec:
  replicas: 1
  strategy:
    type: Rolling
    resources:
      limits:
        cpu: 150m
        memory: 50Mi
      requests:
        cpu: 150m
        memory: 50Mi
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: blackbox
      initContainers:
        - name: wait-for-deployment
          image: 'registry.access.redhat.com/ubi8/ubi-minimal:8.4-208'
          command:
            - /bin/sh
            - '-c'
            - for i in `seq 1 230`; do sleep 10; echo "Waiting for odh-dashboard service to become available..."; if curl -s -k https://odh-dashboard.redhat-ods-applications.svc:8443; then exit 0; fi; done; exit 1
      containers:
      - image: quay.io/prometheus/blackbox-exporter:v0.18.0
        name: blackbox-exporter
        args:
        - --log.level=debug
        - --config.file=/tmp/blackbox.yml
        volumeMounts:
        - name: config-volume
          mountPath: /tmp
        ports:
        - containerPort: 9115
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 50m
            memory: 50Mi
      restartPolicy: Always
      progressDeadlineSeconds: 2400
